### ISSUE TITLE
Hello, when I run this code, the sumo interface does not appear, is this normal?

### ISSUE THREAD

**Issue by FADEAWAY114** [lokesh-c-das/intelligent-self-driving-car#2]
![image](https://github.com/lokesh-c-das/intelligent-self-driving-car/assets/105548396/00b8b505-d936-473c-85b1-c9d8dc2f70f3)

**Comment by lokesh-c-das** [comment]
SUMO files are missing. I will add them shortly.

**Comment by FADEAWAY114** [comment]
> SUMO files are missing. I will add them shortly.

Thank you for your reply and look forward to your recovery of the sumo file
